---
name: TEST
on: workflow_dispatch
jobs:
  load-config:
    runs-on: ubuntu-latest
    outputs:
      matrix-json: ${{ steps.load-matrix.outputs.matrix-json }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Load matrix from JSON file
        id: load-matrix
        run: |
          matrix_data=$(cat .github/workflows/config.json | jq -c .)
          echo "matrix-json=$matrix_data" >> $GITHUB_OUTPUT

  echo-config:
    needs: load-config
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.load-config.outputs.matrix-json) }}
    steps:
      - name: Print matrix values
        run: |
          echo "env1.1: ${{ matrix.env1-1 }}"
          echo "env1.2: ${{ matrix.env1-2 }}"
          echo "env1.3: ${{ matrix.env1-3 }}"
