---
name: TEST
on: workflow_dispatch
jobs:
  load-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Load matrix from JSON file
        id: load-matrix
        run: |
          matrix_data=$(cat .github/workflows/config.json | jq -c .)
          echo "MATRIX_JSON=$matrix_data" >> $GITHUB_ENV

  echo-config:
    needs: load-config
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.env.MATRIX_JSON) }}
    steps:
      - name: Print matrix values
        run: |
          echo "env1.1: ${{ matrix.env1-1 }}"
          echo "env1.2: ${{ matrix.env1-2 }}"
          echo "env1.3: ${{ matrix.env1-3 }}"
