---
name: Release
on: workflow_dispatch
jobs:
  load-json:
    runs-on: ubuntu-latest
    outputs:
      json-file: ${{ steps.load-json.outputs.json-file }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Load data from JSON file
        id: load-json
        run: |
          json_data=$(cat .github/workflows/config.json | jq -c .)
          echo "Loaded json data: $json_data"
          echo "json-file=$json_data" >> $GITHUB_OUTPUT
  use-json:
    needs: load-json
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include: ${{ fromJSON(needs.load-json.outputs.json-file) }} # 동적 설정을 위해 include로 사용
    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v4
      - name: Make tar file
        run: |
          mkdir -p temp
          mkdir -p releases/${{ fromJSON(toJSON(matrix)).folder-name }}
          cp -r config temp
          cp -r tbl temp
          cp -r mp temp
          ls -l temp
          cd temp
          sed -i -e 's/temp1/${{ fromJSON(toJSON(matrix)).env1-1 }}/g' config/env-file
          sed -i -e 's/temp2/${{ fromJSON(toJSON(matrix)).env1-2 }}/g' config/env-file
          sed -i -e 's/temp3/${{ fromJSON(toJSON(matrix)).env1-3 }}/g' config/env-file
          cat config/env-file
          tar -cvf ap-setup.tar *
          mv ap-setup.tar ../releases/${{ fromJSON(toJSON(matrix)).folder-name }}
      - name: Commit and Push Build Artifacts
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Release"
          git push origin HEAD:main
