---
name: Read Json and Load in other job
on: workflow_dispatch
jobs:
  load-json:
    runs-on: ubuntu-latest
    outputs:
      json-file: ${{ steps.load-json.outputs.json-file }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Load data from JSON file
        id: load-json
        run: |
          json_data=$(cat .github/workflows/config.json | jq -c .)
          echo "Loaded json data: $json_data"
          echo "json-file=$json_data" >> $GITHUB_OUTPUT
  use-json:
    needs: load-json
    runs-on: ubuntu-latest
    steps:
      - name: Print json
        env:
          JSON_DATA: ${{ needs.load-json.outputs.json-file }}
        run: |
          echo "json_data: $JSON_DATA"
          echo "json_data: ${JSON_DATA}"
