---
name: Read Json and Use in Strategy Matrix
on: workflow_dispatch
jobs:
  load-json:
    runs-on: ubuntu-latest
    outputs:
      json-file: ${{ steps.load-json.outputs.json-file }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Load data from JSON file
        id: load-json
        run: |
          json_data=$(cat .github/workflows/config.json | jq -c .)
          echo "Loaded json data: $json_data"
          echo "json-file=$json_data" >> $GITHUB_OUTPUT
  use-json:
    needs: load-json
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include: ${{ fromJSON(needs.load-json.outputs.json-file) }} # 동적 설정을 위해 include로 사용
    steps:
      - name: Check
        env:
          MATRIX: ${{ toJSON(matrix) }}
          ENV1: ${{ fromJSON(toJSON(matrix)).env1-1 }}
          ENV2: ${{ fromJSON(toJSON(matrix)).env1-2 }}
          ENV3: ${{ fromJSON(toJSON(matrix)).env1-3 }}
        run: |
          echo "MATRIX: $(jq -r -c '.' <<< "$MATRIX")"
          echo "ENV1: [$ENV1]"
          echo "ENV2: [$ENV2]"
          echo "ENV3: [$ENV3]"
